### PR TITLE
Dutch translation

### PR DESCRIPTION
**Pull request by ghost**
- [x] Title

#### Page 1
- [x] Initial translation (@M1dgard)
- [x] Proofread and correct regional expressions (@Willem3141)
- [x] Adjust geometry

#### Page 2
- [x] Initial translation (@M1dgard)
- [x] Proofread and correct regional expressions (@Willem3141)
- [x] Adjust geometry

#### Page 3
- [x] Initial translation (@M1dgard)
- [x] Proofread and correct regional expressions (@Willem3141)
- [x] Adjust geometry

#### Page 4
- [x] Initial translation (@M1dgard)
- [x] Proofread and correct regional expressions (@Willem3141)
- [x] Adjust geometry

#### Page 5
- [x] Initial translation (@M1dgard)
- [x] Proofread and correct regional expressions (@Willem3141)
- [x] Adjust geometry

#### Page 6
- [x] Initial translation (@M1dgard)
- [x] Proofread and correct regional expressions (@Willem3141)
- [x] Adjust geometry

#### Page 7
- [x] Initial translation (@M1dgard)
- [x] Proofread and correct regional expressions (@Willem3141)
- [x] Adjust geometry

####
- [x] Credits

### CODE REVIEW

**Comment by ghost** [comment]
Ik heb net een alternatieve, allitererende alias bedacht: *het tovertoernooi*

**Comment by Willem3141** [comment]
I'll look at this tonight. Thanks already for the translation of page 1-5 :)

**Comment by Willem3141** [comment]
Okay, it turns out that my Linux distro, Chakra, has updated to Inkscape 0.92, so I cannot edit the files (see David's blog post). I can probably install an old version via my Linux distribution, but I don't have time for that today... To be continued 😃

**Comment by ghost** [comment]
Same story here (plain Arch Linux, also with KDE as it happens). I can't downgrade because Inkscape becomes unstable (probably libs that have been upgraded) so I guess you'll have the same problem. Mc, an Inkscape dev who's been active on the #pepper&carrot IRC channel, suggests building 0.92.1 from source or waiting for its release (which will be soon, I think).

I have been translating the SVG files by just opening them with Kate. Quite convenient that SVG is XML based. :)

**Comment by M1dgard** [comment]
EDIT previous message:
I have been translating the SVG files by just opening them with ~~KDE~~ **Kate**.

**Comment by Willem3141** [comment]
>I have been translating the SVG files by just opening them with Kate. Quite convenient that SVG is XML based. :)

That works (and produces nicer diffs!), however getting the layout right is not really possible.

I can at least check the translations and translate the last page; then in the weekend I will try compiling Inkscape 0.92.1 so I can see whether it looks somewhat right 😉  Thanks for the help!

**Comment by Willem3141** [comment]
Ah, my apologies for the extreme slowness on this one ... I've got two suggestions:

* Page 3: overgaan op -> overgaan tot _(seems more natural to me)_
* Page 5: hemels naam -> hemelsnaam _(https://onzetaal.nl/taaladvies/in-hemelsnaam-in-s-hemelsnaam1)_

If you agree with those, I'll edit them.

**Comment by ghost** [comment]
Allright with me! Thanks for the improvements.

**Pull request merged**
